#!/usr/bin/env perl
use lib 'lib';
use utf8;
use warnings;
use constant debug => $ENV{DEBUG};
use App::witchcraft::Command;
use App::witchcraft::Utils qw(error info);
use File::Path qw(make_path remove_tree);

#use Carp::Always;

$| = 1;

binmode STDOUT, ':utf8';

my $act = shift;

$SIG{INT} = sub {
    exit;
};
make_path ${App::witchcraft::HOME}
    and info "Now you need to setup your witchcraft.conf"
    unless ( -d ${App::witchcraft::HOME} );
error "You must create a proper " . ${App::witchcraft::CONFIG} . " !!" and die
    unless ( -e ${App::witchcraft::CONFIG} );
App::witchcraft::Command->global_help and exit
    if ( defined $act and $act eq "--help" );
App::witchcraft::Command->invoke( ($act), @ARGV );
exit;
